cmake_targets:
  coroutine_task:
    timeout: 30s
    profiles:
      - release-lines
      - asan-lines

submit_files:
  - coroutine.hpp
  - coroutine.cpp

lint_files:
  - test.cpp
  - coroutine.cpp

lint_profiles:
  - release
