cmake_targets:
  fibers_task:
    profiles:
      - release
      - asan
      - tsan

submit_files:
  - fiber.hpp
  - fiber.cpp
  - coro/coroutine.hpp
  - coro/coroutine.cpp
  - tp/queue.hpp
  - tp/tp.hpp
  - tp/tp.cpp
  - tp/wg.hpp
