cmake_targets:
  fibers_task:
    timeout: 3m
    profiles:
      - release
      - asan
      - tsan

submit_files:
  - fiber.hpp
  - fiber.cpp
  - coro/coroutine.hpp
  - coro/coroutine.cpp
  - tp/queue.hpp
  - tp/tp.hpp
  - tp/tp.cpp
  - tp/wg.hpp

lint_files:
  - fiber.cpp
  - coro/coroutine.cpp
  - tp/tp.cpp
  - coro/test.cpp
  - tp/test.cpp

lint_profiles:
  - release
