cmake_targets:
  future_base_task:
    timeout: 30s
    profiles:
      - release
      - asan
      - tsan
      - release-lines
      - asan-lines

  future_combining_task:
    timeout: 30s
    profiles:
      - release
      - asan
      - tsan
      - release-lines
      - asan-lines

submit_files:
  - ../future.hpp
  - ../future.ipp
  - ../future.cpp
  - ../promise.hpp
  - ../promise.ipp
  - ../promise.cpp
  - ../state.hpp
  - ../state.ipp
  - ../combine.ipp
  - ../meta.hpp

lint_files:
  - combining.cpp
  - ../base/base.cpp

lint_profiles:
  - release
