cmake_targets:
  std_future_task:
    timeout: 1m
    profiles:
      - release
      - tsan
      - release-lines
      - asan-lines
      - asan

submit_files:
  - future.hpp
  - promise.hpp
  - state.hpp

lint_files:
  - test.cpp

lint_profiles:
  - release
