cmake_targets:
  thread_pool_task:
    timeout: 3m
    profiles:
      - release-lines
      - asan-lines
      - release
      - asan
      - tsan

submit_files:
  - queue.hpp
  - tp.hpp
  - tp.cpp
  - wg.hpp

lint_files:
  - test.cpp
  - tp.cpp

lint_profiles:
  - release
