#!/usr/bin/env bash

nix_version=$(nix --version 2> /dev/null)

if [[ $? -ne 0 ]]; then
  printf "Installing nix\n"
  sh <(curl -L https://nixos.org/nix/install) --yes

  if [[ $(uname) == "Darwin" ]]; then
    mkdir -p ~/.config/nix
    if ! grep "system = x86_64-darwin" ~/.config/nix/nix.conf > /dev/null; then
      echo "system = x86_64-darwin" >> ~/.config/nix/nix.conf
    fi
    source /nix/var/nix/profiles/default/etc/profile.d/nix.sh
  else
    source ~/.nix-profile/etc/profile.d/nix.sh
  fi
fi

nix_version=$(nix --version)

if [[ $? -ne 0 ]]; then
  printf "I'm unable to install Nix. Please try reloading the terminal.\n"
  printf "If this does not help, please contact the course support team for assistance and attach full logs.\n"
  return 1
else
  printf "Using $nix_version\n"
fi

nix --experimental-features 'nix-command flakes' develop ./env $@
